[package]
name = "fleece-rs"
version = "0.1.0"
edition = "2021"

[profile.release]
codegen-units = 1

[dependencies]
thiserror = "1.0.56"

[dev-dependencies]
criterion = { version = "0.5.1" }

[profile.bench]
codegen-units = 1
opt-level = 2

[[bench]]
name = "decode"
harness = false

[[bench]]
name = "encode"
harness = false

[lints.clippy]
pedantic = { priority = -1, level = "warn" }
module_name_repetitions = "allow"
