[package]
name = "fleece-rs"
version = "0.1.0"
edition = "2021"

[profile.release]
codegen-units = 1

[dependencies]

[dev-dependencies]
criterion = { version = "0.5.1" }

[[bench]]
name = "decode"
harness = false
